version: '3'

services:
  cataas_back:
    build: ./cataas_back
    ports:
      - 4000:4000
    volumes:
      - ./cataas_back:/home/node/app
    entrypoint: sh -c "npm install && npm start run:dev"

  catass_front:
    build: ./catass_front
    ports:
      - 3000:3000
    volumes:
      - ./catass_front:/home/node/app
    entrypoint: sh -c "npm install && npm run dev"
    depends_on:
      - cataas_back  


  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_cataas   
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql  


  redis:
      image: redis:7.0-alpine
      ports:
        - 6379:6379


volumes:
  mysql_data:
    driver: local